# 测试我们的算法

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target
X.shape

(150, 4)

In [7]:
y.shape

(150,)

# train_test_split

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
shuffle_indexes = np.random.permutation(len(X))
# 0 - 150的随机排列
shuffle_indexes

array([ 28, 107,  75, 121, 147,   8, 149,  53,  13,  93, 138,   3,  24,
        35,  95,  22,  70,  44, 125,  34, 114,  92, 142,  88,  12,  89,
       109,  11, 145,  10, 134,  94,  37,  86,  74,  38,   1, 139,  26,
        36, 146,  33,  15,   5,  99,   0, 117, 130,  67,  39,  85, 141,
       129,  69,  55,  80,  71,   2,  51,  17, 103, 101,  47,  72,  31,
        18, 112, 126, 105,  96, 100,  23,  97, 106,  64,  76,  16,  40,
       120, 148,  21,  48, 143, 131, 128,  81,  83, 144,  91,  58,  82,
        77, 136,  45, 122, 133, 124, 135,  73,  66, 104, 119, 132,  78,
       127, 123, 116,  19,   6,   9,  98, 118,  60,  41,  90,  62,   7,
       113, 140, 115,  52,  65,  84, 137, 102,  63,  79,   4,  27,  57,
        14,  25,  87,  50,  54,  43, 108,  59,  29,  42,  49,  56,  32,
        20, 110,  46,  68,  61, 111,  30])

In [14]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [16]:
test_indexes = shuffle_indexes[:test_size]
test_indexes

array([ 28, 107,  75, 121, 147,   8, 149,  53,  13,  93, 138,   3,  24,
        35,  95,  22,  70,  44, 125,  34, 114,  92, 142,  88,  12,  89,
       109,  11, 145,  10])

In [17]:
train_indexes = shuffle_indexes[test_size:]
train_indexes

array([134,  94,  37,  86,  74,  38,   1, 139,  26,  36, 146,  33,  15,
         5,  99,   0, 117, 130,  67,  39,  85, 141, 129,  69,  55,  80,
        71,   2,  51,  17, 103, 101,  47,  72,  31,  18, 112, 126, 105,
        96, 100,  23,  97, 106,  64,  76,  16,  40, 120, 148,  21,  48,
       143, 131, 128,  81,  83, 144,  91,  58,  82,  77, 136,  45, 122,
       133, 124, 135,  73,  66, 104, 119, 132,  78, 127, 123, 116,  19,
         6,   9,  98, 118,  60,  41,  90,  62,   7, 113, 140, 115,  52,
        65,  84, 137, 102,  63,  79,   4,  27,  57,  14,  25,  87,  50,
        54,  43, 108,  59,  29,  42,  49,  56,  32,  20, 110,  46,  68,
        61, 111,  30])

In [18]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [19]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [20]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


# 使用我们的算法

In [23]:
from playML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [25]:
from playML.KNN import KNNClassifier
my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [26]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([0, 0, 2, 1, 1, 1, 0, 2, 0, 1, 1, 2, 1, 0, 2, 2, 1, 0, 0, 0, 2, 1,
       0, 2, 0, 1, 1, 1, 0, 0])

In [27]:
y_test

array([0, 0, 2, 1, 1, 1, 0, 2, 0, 1, 2, 2, 2, 0, 2, 2, 1, 0, 0, 0, 2, 1,
       0, 2, 0, 1, 1, 1, 0, 0])

In [29]:
y_predict == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [30]:
sum(y_predict == y_test) / len(y_test)

0.9333333333333333

# sklearn中的train_test_split

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [33]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [36]:
?train_test_split