In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.3'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.14.3'

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.random.randint(0, 10)

6

In [14]:
np.random.randint(4, 8, size=(3,5))

array([[4, 7, 5, 5, 4],
       [4, 7, 4, 4, 7],
       [7, 6, 4, 5, 5]])

In [15]:
np.random.randint(4, 8, size=10)

array([7, 7, 7, 5, 4, 4, 4, 4, 6, 6])

In [16]:
np.random.randint(4, 8, size=(3,5))

array([[6, 6, 7, 5, 5],
       [4, 7, 6, 6, 4],
       [7, 7, 4, 6, 5]])

In [17]:
np.random.seed(666)
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [18]:
np.random.seed(666)
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [19]:
np.random.random(10)

array([0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656,
       0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555])

In [20]:
np.random.normal()

0.40180184207150565

In [21]:
np.random.normal?

In [22]:
X = np.arange(15).reshape(3, 5)

In [23]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
x = np.arange(10)

In [25]:
x
x.ndim

1

In [26]:
X.ndim

2

In [27]:
x.shape

(10,)

In [28]:
X.shape

(3, 5)

In [29]:
x.size

10

In [30]:
X.size

15

In [31]:
x[0]

0

In [32]:
x[-1]

9

In [33]:
X[0][0]

0

In [34]:
X[0,0]

0

In [35]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [36]:
x[5:]

array([5, 6, 7, 8, 9])

In [37]:
X[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [38]:
x[::2]

array([0, 2, 4, 6, 8])

In [39]:
X[0, :]

array([0, 1, 2, 3, 4])

In [40]:
X[0]

array([0, 1, 2, 3, 4])

In [41]:
X[:, 0]

array([ 0,  5, 10])

In [42]:
subX = X[:2, :3]

In [43]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [44]:
subX[0, 0] = 100

In [45]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [46]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [47]:
A = x.reshape(2, 5)

In [48]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
B = x.reshape(1, 10)

In [51]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [53]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

合并操作

In [56]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [58]:
x

array([1, 2, 3])

In [59]:
y

array([3, 2, 1])

In [60]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [62]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
z = np.array([666, 666, 666])
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [65]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [66]:
B = np.full((2, 2), 100)

In [67]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

# 分割操作

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x1, x2, x3 = np.split(x, [3, 7])

In [72]:
x1

array([0, 1, 2])

In [73]:
x2

array([3, 4, 5, 6])

In [74]:
x3

array([7, 8, 9])

In [75]:
A = np.arange(16).reshape((4, 4))

In [77]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
A1, A2 = np.split(A, [2])

In [79]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [80]:
A1, A2 = np.hsplit(A, [2])

In [81]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [82]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])