In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(2*e)
A    

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
import numpy as np
L = np.arange(n)

In [9]:
%%time
A = 2 * L
A

CPU times: user 21 µs, sys: 0 ns, total: 21 µs
Wall time: 26 µs


# Universal Functions

In [10]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [12]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [13]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [14]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [15]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [16]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [17]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [18]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [19]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [20]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [22]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [24]:
A + B

array([[10, 11],
       [12, 13]])

In [25]:
A * B

array([[ 0, 10],
       [20, 30]])

In [26]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [27]:
A.T

array([[0, 2],
       [1, 3]])

In [28]:
v = np.array([1, 2])

In [29]:
A

array([[0, 1],
       [2, 3]])

In [30]:
v + A

array([[1, 3],
       [3, 5]])

In [31]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [32]:
v * A

array([[0, 2],
       [2, 6]])

In [33]:
v.dot(A)

array([4, 7])

In [34]:
A

array([[0, 1],
       [2, 3]])

In [38]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [39]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [40]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [41]:
X = np.arange(16).reshape(2, 8)

In [42]:
invX = np.linalg.pinv(X)
invX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [43]:
invX.shape

(8, 2)

In [44]:
X.dot(invX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])