In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.9541747 , 0.95530259, 0.4778605 , 0.98551309, 0.59238984,
       0.2478112 , 0.34538101, 0.86739747, 0.21535671, 0.72971518,
       0.29021871, 0.98985014, 0.98753595, 0.05425247, 0.66861426,
       0.00663305, 0.01980202, 0.90326491, 0.81593832, 0.19487997,
       0.39574787, 0.30193709, 0.62608468, 0.08673205, 0.07713311,
       0.50945431, 0.32247521, 0.69595566, 0.23751912, 0.18637771,
       0.88548386, 0.03534664, 0.41339145, 0.72810277, 0.30111925,
       0.14909794, 0.26448119, 0.1833749 , 0.64049017, 0.91059045,
       0.39067723, 0.58664182, 0.95859318, 0.29751056, 0.04559264,
       0.37190702, 0.03731127, 0.74345622, 0.89648502, 0.23524781,
       0.93296511, 0.91238351, 0.37157782, 0.19171372, 0.81530341,
       0.85414895, 0.47517179, 0.45783148, 0.62102422, 0.34184427,
       0.72241579, 0.66154412, 0.47369334, 0.99942928, 0.99518506,
       0.62705404, 0.87723606, 0.34253966, 0.19881727, 0.78965752,
       0.98981287, 0.30268449, 0.96045239, 0.45130104, 0.44249

In [4]:
sum(L)

49.6503682757233

In [5]:
np.sum(L)

49.65036827572332

In [6]:
np.min(L)

0.006633048503636663

In [7]:
L.max()

0.9994292783812142

In [8]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.sum(X)

120

In [10]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [11]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [13]:
np.prod(X)

0

In [14]:
np.prod(X + 1)

20922789888000

In [15]:
np.mean(X)

7.5

In [16]:
np.median(X)

7.5

In [17]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [18]:
np.median(v)

2.0

In [20]:
x = np.random.normal(0, 1, size=100)

In [21]:
np.mean(x)

0.039972744113009114

In [22]:
np.std(x)

0.9736561476853834

# 索引

In [23]:
np.min(x)

-2.6414999087733895

In [24]:
np.argmin(x)

39

In [25]:
x[39]

-2.6414999087733895

In [27]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
np.random.shuffle(x)
x

array([ 3,  1, 12,  7, 15,  8,  5, 14,  2, 13, 11,  4,  0,  9, 10,  6])

In [29]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
x

array([ 3,  1, 12,  7, 15,  8,  5, 14,  2, 13, 11,  4,  0,  9, 10,  6])

In [31]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
X = np.random.randint(10, size=(4,4))
X

array([[6, 6, 3, 0],
       [9, 8, 3, 9],
       [2, 3, 5, 8],
       [6, 7, 9, 4]])

In [33]:
np.sort(X)

array([[0, 3, 6, 6],
       [3, 8, 9, 9],
       [2, 3, 5, 8],
       [4, 6, 7, 9]])

In [34]:
np.sort(X, axis=0)

array([[2, 3, 3, 0],
       [6, 6, 3, 4],
       [6, 7, 5, 8],
       [9, 8, 9, 9]])

In [ ]:
x